server:
  port: 8081

#系统自定义配置
webframe:
  kaptcha-open: true
  file-upload-path: /Users/wanghuidong/Downloads



###################  MyBatis 配置  ###################
mybatis:
  type-aliases-package: com.smallow.webframe.modular.system.model
  mapper-locations: classpath:mapper/*.xml

##################  MyBatis 通用mapper配置  #########################
mapper:
  mappers: com.smallow.webframe.common.mybatis.MyMapper
  not-empty: false
  identity: MYSQL
###################  MyBatis 分页插件配置  ###################
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  freemarker:
    prefix: /WEB-INF/view/
    #suffix: .html
    template-loader-path: classpath:/
    request-context-attribute: request
    cache: false




---
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://119.29.156.83:3306/badminton_barV2.0
    username: root
    password: Zxy@19860122
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
logging:
  level:
    root: info
    com.smallow: debug

---
##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://119.29.156.83:3306/badminton_barV2.0
    username: root
    password: Zxy@19860122
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true